# Generated by Django 4.2.5 on 2023-09-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=100)),
                ('valoracio', models.CharField(max_length=1000)),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.space')),
            ],
        ),
    ]
