# Generated by Django 4.2.5 on 2023-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('espai', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefon', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.URLField(blank=True, max_length=500, null=True)),
                ('coordenades', models.CharField(max_length=100)),
            ],
        ),
    ]
